#!/usr/bin/env groovy
pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = credentials('AWS_DEFAULT_REGION')
        AWS_EKS_CLUSTER_NAME = credentials('AWS_EKS_CLUSTER_NAME')
    }

    stages {
        stage("Destroy EKS Cluster") {
            steps {
                script {
                    dir('../../EKS-cluster') {
                        sh "terraform init --backend-config=dev-backend.tfvars"
                        sh "terraform plan"
                        sh "terraform destroy -auto-approve"
                    }
                }
            }
        }
    }
}
